# Generated by Django 2.2.5 on 2019-10-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190915_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b')], max_length=200),
        ),
    ]
